# name: CD

# on:
#   push:
#     branches:
#       - main
#       - development

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Pull image
#         run: |
#           docker pull ${{ secrets.DOCKER_USERNAME }}/mi-app-angular:${{ github.sha }}

#       - name: Deploy
#         run: |
#           docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/mi-app-angular:${{ github.sha }}
#           curl -s -o /dev/null -w "%{http_code}" http://localhost