name: CD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted,dfauben]
    environment: ${{ inputs.environment }}
    env:
      IMAGE: ${{ inputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${IMAGE}

      - name: Run Nginx Container
        run: |
          docker run -d --name $CONTAINER_NAME -p 8080:8080 $IMAGE
          for i in {1..10}; do
            if curl -sSf http://localhost:8080 >/dev/null; then
              echo "✅ Nginx is up"
              break
            else
              echo "⌛ Waiting for Nginx... ($i/10)"
              sleep 2
            fi
          done
 
      - name: Smoke Test with curl
        run: |
          STATUS=$(curl -o /dev/null -w '%{http_code}' http://localhost:8080)
          [ "$STATUS" -eq 200 ] && echo "✅ Smoke test passed" || (echo "❌ Got $STATUS" && exit 1)
 
      - name: Cleanup
        if: always()
        run: docker rm -f $CONTAINER_NAME