name: CD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted,dfauben]
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/mi-app-angular:0.0.0

      - name: Deploy
        run: |
          docker run -d -p 80:80 ${{ vars.DOCKER_USERNAME }}/mi-app-angular:0.0.0
          curl -s -o /dev/null -w "%{http_code}" http://localhost