name: CD

on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted,dfauben]
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/mi-app-angular:${{ env.IMAGE }}

      - name: Deploy
        run: |
          docker run -d -p 80:80 ${{ vars.DOCKER_USERNAME }}/mi-app-angular:${{ env.IMAGE }}
          curl -s -o /dev/null -w "%{http_code}" http://localhost