name: CI

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag image
        uses: ./.github/workflows/tag-image.yml
        id: tag
        with:
          image_name: ${{ secrets.DOCKER_USERNAME }}/mi-app-angular
          version: $(cat package.json | jq -r '.version')

      - name: Build and push image
        run: |
          docker build -t ${{ steps.tag.outputs.tagged_image }} .
          docker push ${{ steps.tag