name: CI

on:
   push:
     branches:
       - main
       - development

jobs:
  build-and-push:
    runs-on: [self-hosted,dfauben]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extraer versión de package.json
        run: |
          VERS=$(jq -r '.version' package.json)
          echo "VERSION=$VERS" >> $GITHUB_ENV

      - id: tag-image
        uses: ./.github/actions/tag-image
        with:
          image_name: ${{ vars.DOCKER_USERNAME }}/mi-app-angular
          version: $VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Usar la imagen etiquetada
        run: echo "IMAGE=${{ steps.tag-image.outputs.tagged_image }}" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}