name: CI

on:
   push:
     branches:
       - main
       - development

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag image
        uses: ./.github/actions/tag-image/action.yml
        id: tag
        with:
          image_name: ${{ secrets.DOCKER_USERNAME }}/mi-app-angular
          version: $(cat package.json | jq -r '.version')

      - name: Build and push image
        run: |
          docker build -t ${{ steps.tag.outputs.tagged_image }} .
          docker tag ${{ steps.tag.outputs.tagged_image }} ${{ secrets.DOCKER_USERNAME }}/mi-app-angular:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mi-app-angular:latest