name: CI

on:
   push:
     branches:
       - main
       - development

jobs:
  build-and-push:
    runs-on: [self-hosted,dfauben]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag image
        uses: ./.github/actions/tag-image
        id: tag
        with:
          image_name: ${{ secrets.DOCKER_USERNAME }}/mi-app-angular
          version: $(cat package.json | jq -r '.version')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Usar la imagen etiquetada
        run: echo "La imagen etiquetada es ${{ steps.tag-image.outputs.tagged_image }}"
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ../../Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.tagged_image }}