name: Angular app CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  Continuous_Integration:
    uses: ./.github/workflows/ci.yml
    with:
      username: ${{ vars.DOCKER_USERNAME }}


  Continuous_Deployment:
    needs: Continuous_Integration
    uses: ./.github/workflows/cd.yml
    with:
      username: ${{ vars.DOCKER_USERNAME }}
      # password: ${{ secrets.DOCKER_TOKEN }}