name: CD

on:
  push:
    branches:
      - main
      - development

jobs:
  Continuous_Integration:
    uses: ./.github/workflows/ci.yml

  Continuous_Deployment:
    needs: Continous_Integration
    uses: ./.github/workflows/cd.yml