name: Angular app CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  Continuous_Integration:
    uses: ./.github/workflows/ci.yml
    with:
      env: ${{ github.ref_name == 'main' && 'production' || (github.ref_name == 'development' && 'UAT' || 'UAT') }}


  Continuous_Deployment:
    needs: Continuous_Integration
    uses: ./.github/workflows/cd.yml
    with:
      env: ${{ github.ref_name == 'main' && 'production' || (github.ref_name == 'development' && 'UAT' || 'UAT') }}
